// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWpJMLkQDjHtknC0YbsuEnVrEEkXvm0A',
    appId: '1:60188913236:web:e51ffeaf3f65b5c75847c1',
    messagingSenderId: '60188913236',
    projectId: 'spotify02-271bc',
    authDomain: 'spotify02-271bc.firebaseapp.com',
    storageBucket: 'spotify02-271bc.firebasestorage.app',
    measurementId: 'G-X3FPLS4CBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDrI5RXKc5azGCC9j1BXcNO1C9erXJXM',
    appId: '1:60188913236:android:0f21a5fc45ea1c7c5847c1',
    messagingSenderId: '60188913236',
    projectId: 'spotify02-271bc',
    storageBucket: 'spotify02-271bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANqDpFc3r9Cm73L-FE2h1UStov9f5gwQ',
    appId: '1:60188913236:ios:492e8f20910ecb4a5847c1',
    messagingSenderId: '60188913236',
    projectId: 'spotify02-271bc',
    storageBucket: 'spotify02-271bc.firebasestorage.app',
    iosBundleId: 'com.example.spotifymusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBANqDpFc3r9Cm73L-FE2h1UStov9f5gwQ',
    appId: '1:60188913236:ios:492e8f20910ecb4a5847c1',
    messagingSenderId: '60188913236',
    projectId: 'spotify02-271bc',
    storageBucket: 'spotify02-271bc.firebasestorage.app',
    iosBundleId: 'com.example.spotifymusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByWpJMLkQDjHtknC0YbsuEnVrEEkXvm0A',
    appId: '1:60188913236:web:d16ed6811dec23ec5847c1',
    messagingSenderId: '60188913236',
    projectId: 'spotify02-271bc',
    authDomain: 'spotify02-271bc.firebaseapp.com',
    storageBucket: 'spotify02-271bc.firebasestorage.app',
    measurementId: 'G-9WJNVD2TEQ',
  );
}
